### Data type in python

In [5]:
# Dynamic type
# int, str, float, boolean

In [18]:
# List
# methods https://www.w3schools.com/python/python_lists_methods.asp
x = [1,2,2,3,3,3,1,2,3,2,4,4,5,6,4]
for i in x:
    print(i)
    print(type(i))

1
<class 'int'>
2
<class 'int'>
2
<class 'int'>
3
<class 'int'>
3
<class 'int'>
3
<class 'int'>
1
<class 'int'>
2
<class 'int'>
3
<class 'int'>
2
<class 'int'>
4
<class 'int'>
4
<class 'int'>
5
<class 'int'>
6
<class 'int'>
4
<class 'int'>


In [20]:
print(x.count(3))


4


In [25]:
# Tuple
# methods https://www.w3schools.com/python/python_ref_tuple.asp
tuple_1 = (1,2,3)
print('index', tuple_1.index(2))
print('value', tuple_1[1])

index 1
value 2


In [33]:
# Dict
# methods https://www.w3schools.com/python/python_ref_dictionary.asp
dict_1 = {'phone': 'iphone-13', 'price': 2500}
dict_2 = {'phone': 'Galaxy note 12', 'price': 1500, 'brand': 'samsung'}
print(dict_2['phone'])
print(dict_2['price'])
print(dict_2.get('brand', 'brand not registered'))

Galaxy note 12
1500
samsung


In [84]:
dict_2 = {'phone': 'Galaxy note 12',
          'price': 1500,
          'brand': 'samsung',
          'phone': 'z-flip'}
print(dict_2)

{'phone': 'z-flip', 'price': 1500, 'brand': 'samsung'}


In [44]:
dict_2 = {'phone': 'Galaxy note 12', 'price': 1500, 'brand': 'samsung'}

for k, v in dict_1.items():
    print('key_name:', k, ', value:', v)

key_name: phone , value: iphone-13
key_name: price , value: 2500


In [45]:
print('keys:', dict_2.keys())
print('values:', dict_2.values())

keys: dict_keys(['phone', 'price', 'brand'])
values: dict_values(['Galaxy note 12', 1500, 'samsung'])


In [39]:
phones =[
    {'model': 'iphone-13', 'price': 2500},
    {'model': 'Galaxy note 12', 'price': 1500, 'brand': 'samsung'},
    {'model': 'pixel XL', 'brand': 'google'},
]

for phone in phones:
    print('Brand:', phone.get('brand', 'unidentified brand'))
    print('model:', phone['model'])
    print('price: $', phone.get('price', 0))
    print('===========================')
    

Brand: unidentified brand
model: iphone-13
price: $ 2500
Brand: samsung
model: Galaxy note 12
price: $ 1500
Brand: google
model: pixel XL
price: $ 0


In [46]:
# Set
#  methods https://www.w3schools.com/python/python_ref_dictionary.asp
list_1 = [1,2,2,3,3,3,1,2,3,2,4,4,5,6,4]
set_1 = set(list_1)
print(list_1)
print(set_1)

[1, 2, 2, 3, 3, 3, 1, 2, 3, 2, 4, 4, 5, 6, 4]
{1, 2, 3, 4, 5, 6}


In [49]:
set_1.add(0)
print(set_1)

{0, 1, 2, 3, 4, 5, 6, 7}


### Slicing list/tuple dsb

In [66]:
data = [21,23,22,43,56,79,90,200,30,40,50,55,55,90]
# indexing
# index ke 2
print(data[2])
# index ke 10
print(data[10])

# slicing
# value expected 56,79,90,200,30,40,50,55
# start: 4 end:12
print(data[4:12])

# values expected 21,23,22,43,56,79,90,200
# start: 0 end: 8
print(data[:8])

# values expected 79,90,200,30,40,50,55,55,90
# start: 6 end: 14
print(data[6:])

22
50
[56, 79, 90, 200, 30, 40, 50, 55]
[21, 23, 22, 43, 56, 79, 90, 200]
[90, 200, 30, 40, 50, 55, 55, 90]


In [59]:
print('last index of data:', data[-1])

last index of data: 90


In [69]:
print(data)
print(data[::-1])

[21, 23, 22, 43, 56, 79, 90, 200, 30, 40, 50, 55, 55, 90]
[90, 55, 55, 50, 40, 30, 200, 90, 79, 56, 43, 22, 23, 21]


### ndArray in numpy
reference https://numpy.org/doc/stable/reference/arrays.ndarray.html

In [70]:
import numpy as np

In [71]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [75]:
matrix_list = np.arange(32).reshape(4,8)

In [76]:
matrix_list

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [80]:
#  expected
# 12, 13
# 20, 21

matrix_list[1:3, 4:6]

array([[12, 13],
       [20, 21]])

In [83]:
# expected 5, 13, 21, 29
matrix_list[:, 5]

array([ 5, 13, 21, 29])